"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path");
const { fixture } = require("../support/runtime.js");
const { normalizeRuntimeConfig } = require("../../internal/instance/config.js");
const { createRuntimeBootstrap } = require("../../internal/runtime/bootstrap.js");
const { createFileBrowser } = require("../../internal/library/file-browser.js");
const { MIME } = require("../../internal/media/service.js");
test("source links, stable shares and authorized VTT survive generation replacement", async t => {
  const f = await fixture(t, { empty: true });
  f.work("sample # unicode", { title: "Synthetic", url: "https://example.invalid/post/1", user: { name: "Sample" } }, { "clip.webm": "fake video", "clip.zh-CN.vtt": "WEBVTT\n\n00:00.000 --> 00:01.000\nSynthetic\n" });
  await f.build(); f.publish(); let runtime = createRuntimeBootstrap({ config: f.config }); f.cleanup.push(() => runtime.close()); await runtime.start();
  const get = async url => (await (await fetch(f.config.url+url)).json()).data;
  const work = (await get("/api/v1/works")).items[0];
  assert.equal(work.sourceUrl, "https://example.invalid/post/1");
  const detail = await get("/api/v1/works/"+work.id); assert.equal(detail.media.length, 1);
  const subtitle = "/api/v1/subtitles/"+detail.media[0].id+"?g=first&lang=zh-CN";
  const response = await fetch(f.config.url+subtitle); assert.equal(response.status,200); assert.match(response.headers.get("content-type"),/^text\/vtt/); assert.match(await response.text(),/^WEBVTT/);
  assert.equal((await fetch(f.config.url+subtitle,{method:"HEAD"})).status,200);
  assert.equal((await fetch(f.config.url+subtitle.replace("zh-CN","../secret"))).status,400);
  const share = await fetch(f.config.url+"/api/v1/short-links",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:work.stableId,media:"clip.webm"})});
  assert.equal(share.status,200);const link=(await share.json()).data;assert.ok(!link.target.includes("g="));assert.match(link.target,/%23/);
  const legacy=await fetch(f.config.url+"/api/shorten",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:work.stableId,media:"clip.webm",ver:"https://example.invalid",page:2})});const legacyLink=await legacy.json();assert.equal(legacyLink.code,link.code);assert.equal(legacyLink.target,link.target);
  assert.equal((await fetch(f.config.url+"/api/v1/short-links",{method:"POST",body:JSON.stringify({path:"https://example.invalid/"})})).status,400);
  await runtime.close();f.work("000-new",undefined);await f.build("second");f.publish("second");runtime=createRuntimeBootstrap({config:f.config});await runtime.start();
  await new Promise(resolve => setTimeout(resolve,100));
  const redirect = await fetch(f.config.url+link.url,{redirect:"manual"});assert.equal(redirect.status,302);assert.equal(redirect.headers.get("location"),link.target);
  const same = await get("/api/v1/resolve?path="+encodeURIComponent(work.stableId));assert.equal(same.item.sourceUrl,work.sourceUrl);assert.notEqual(same.item.id,work.id);
  for(const ext of ["bmp","ico","tif","tiff","avi","ogv"])assert.ok(MIME["."+ext]);
});
test("bounded file search excludes registered platforms from every file route", async t => {
  const f=await fixture(t,{empty:true});f.work("secret sample",undefined);const root=path.dirname(f.bindings.pixiv);
  fs.mkdirSync(path.join(root,"outside"));for(const name of ["sample1.png","sample2.png","sample10.png"])fs.writeFileSync(path.join(root,"outside",name),f.PNG);
  const config=normalizeRuntimeConfig({...f.config,fileBrowserRoots:[{id:"files",name:"Synthetic",path:root}]});const browser=createFileBrowser(config);
  const rel=path.relative(root,f.bindings.pixiv).replace(/\\/g,"/");assert.throws(()=>browser.list("files",rel),{code:"FILE_PLATFORM_EXCLUDED"});assert.throws(()=>browser.mediaFile("files",rel+"/100/secret sample/1.png"),{code:"FILE_PLATFORM_EXCLUDED"});
  const a=await browser.search("files","",{query:"sample",pageSize:2});assert.equal(a.total,3);assert.deepEqual(a.items.map(m=>m.name),["sample1.png","sample2.png"]);
  const b=await browser.search("files","",{query:"sample",pageSize:2,page:2});assert.equal(b.items[0].name,"sample10.png");
  assert.equal((await browser.search("files","",{query:"sample",maxEntries:1})).truncated,true);
  await assert.rejects(browser.search("files","",{query:"sample",signal:AbortSignal.abort()}),{code:"REQUEST_CANCELLED"});
  assert.throws(()=>browser.list("files","../"));
});
